[build]
  command = "npm run prisma:migrate:deploy && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  functions = "netlify/functions"
  targetPort = 5176
  port = 8888
